name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unbound:$(date +%s)
    - name: Auth to Docker registry
      env:
        unbound_pat: ${{ secrets.unbound_pat }}
        github_username: ${{ secrets.github_username }}
      run: docker login docker.pkg.github.com -u $github_username -p $unbound_pat
    - name: Tag Image
      run:  docker tag unbound:$(date +%s) docker.pkg.github.com/patrickbeam/unbound/unbound:$(date +%s)
    - name: Publish Image
      run: docker push docker.pkg.github.com/patrickbeam/unbound/unbound:$(date +%s)
